### ISSUE TITLE
CONFIG_SILEAD_DMI

### ISSUE THREAD

**Issue by nerijus** [maurossi/linux#12]
It seems silead_dmi.c is not compiled, as CONFIG_SILEAD_DMI is not set.
Could you please enable this option? It is needed for my Onda obook 20 plus tablet in order to recognize axes and touch screen size. drivers/platform/x86/silead_dmi.c contains:
```
static const struct property_entry onda_obook_20_plus_props[] = {
       PROPERTY_ENTRY_U32("touchscreen-size-x", 1728),
       PROPERTY_ENTRY_U32("touchscreen-size-y", 1148),
       PROPERTY_ENTRY_BOOL("touchscreen-inverted-x"),
       PROPERTY_ENTRY_BOOL("touchscreen-inverted-y"),
       PROPERTY_ENTRY_BOOL("touchscreen-swapped-x-y"),
       PROPERTY_ENTRY_STRING("firmware-name", "gsl3676-onda-obook-20-plus.fw"),
       PROPERTY_ENTRY_U32("silead,max-fingers", 10),
       PROPERTY_ENTRY_BOOL("silead,home-button"),
       { }
```
Without silead_dmi.c kernel tries to use default silead firmware mssl1680.fw instead of gsl3676-onda-obook-20-plus.fw.

**Comment by nerijus** [comment]
CONFIG_SILEAD_DMI is enabled in kernel-4.16, thanks!

**Comment by nerijus** [comment]
CONFIG_SILEAD_DMI has been renamed to CONFIG_TOUCHSCREEN_DMI. Could you please enable it?

**Comment by maurossi** [comment]
CONFIG_TOUCHSCREEN_DMI=m is now set in the defconfig files
