### ISSUE TITLE
BD PROCHOT cpu throttling (msr read and write)

### ISSUE THREAD

**Issue by imad07mos** [maurossi/linux#14]
Hello , lot of intel laptops suffers from BD PROCHOT flag that throttles cpu when charging , its easily fixable in windows using throttlestop and linux using msr tools 

me and my friend tried to port msr tools to android x86 and compiled it using ndk in Android 7.x source

copied binary files and chmoded them then modprobe msr

rdmsr 0x1FC

it returns this error "rdmsr: open : no such file or directory"

here is the source code of what my friend compiled 

https://github.com/hmtheboy154/msr-tools-android

reference : 

https://github.com/DivyanshuVerma/throttlestop-linux

**Comment by maurossi** [comment]
Hi, this is not the way issues are meant to be used for.
These kind of requests are to be addressed in android-x86 forum
Closing immediately
