### ISSUE TITLE
Wrong audio sample frequency on 280x amdgpu through displayport

### ISSUE THREAD

**Issue by vhda** [maurossi/linux#16]
Hi Mauro,
I tested your kernel-5.8rc5_si_next branch to see if the DC support would finally fix my GPU audio transmission through Display Port in amdgpu, but it doesn't.
I have an Asus VG248QE that supports 144Hz, which I can only use while connecting through Display Port. If I use HDMI I can only go up to 60Hz but audio on the monitor is ok. When using Display Port I can go up to 144Hz but audio comes up distorted (kind like if I was hearing it in slow motion). This happens independently of the active refresh rate.
If you feel like this is not the place to report the issue then I would kindly ask you to at least direct towards the place I should report on as well as which information I should share and how to obtain it.

Thanks in advance,
Vitor

**Comment by mirh** [comment]
If this happens already without DC (and with radeon), I would guess you'd better report this directly [here](https://gitlab.freedesktop.org/drm/amd/-/issues). 
It's already hard enough to get this landed without extra issues /s.

**Comment by vhda** [comment]
Will do, thanks!
