### ISSUE TITLE
Dell Venue 8 Pro 5830

### ISSUE THREAD

**Issue by pwdonald** [maurossi/linux#6]
It seems that with the latest versions of this kernel WIFI has stopped working with the Dell Venue 8 Pro.

It connects but regardless of settings says, "No internet Connection"

AFAIK the adapter is: Dell Wireless 1538

It works with android x86 default kernel 4.9 so I assumed that anything 4.9+ would just add additional functionality but it seems that there are some regression issues?

**Comment by maurossi** [comment]
Hi Donald,

most probably not a kernel regression but system/netd issue,
as we speak in order to have eth and wifi working
we are using the following povilas hack in system/netd
 
https://github.com/maurossi/netd/commit/cc0f660bef98d7ec7d5bb3c48834a83767c54ea4

if you apply the hack in system/netd project both kernel 4.12 and 4.13rc1 are working
Mauro

**Comment by pwdonald** [comment]
Thank you! I will apply this.
If you don't mind me asking, how did you track down the issue? I would like to learn so that I can contribute in the future.

I'm a bit confused as to why the behavior in android-x86 is so much different than Arch Linux or Debian. With this system on Debian I can boot without "nomodeset" parameter but it seems no matter what kernel or version of android x86 I use--I cannot boot with nomodeset.

**Comment by maurossi** [comment]
Hi,
I had barely seen that netlink was returning invalid argument error
and that system/netd in nougat is not latest version
I tried to build more recent version in AOSP, but It did not solve

Povilas has provided the hack to ignore the error:

https://groups.google.com/forum/#!searchin/android-x86/netd|sort:date/android-x86/2F27zlYouQY/6RE-HhO3AAAJ

**Comment by pwdonald** [comment]
I applied the hack and recompiled but the wifi issue remains. 

Kernel 4.13-rc1 (and 4.12)
1. Wifi is disabled on boot.
2. Manually turn on Wifi, connect to AP.
3. Wifi works for 5-10 minutes, then disconnects.
4. Reconnect Wifi but DNS resolution fails.
5. Reboot is required for Wifi to start working again.

**Comment by maurossi** [comment]
Hi,
1. and 2. are in this way in the android-x86 repo
there is no change to atheros driver in this repo compared to kernel 4.12 and kernel 4.13 is rc1.
Closing the issue on github linux

Please post on android-x86 forum with dmesg kernel error for atheros and we will see if somenthing similar pops-up in linux distributions

Mauro
