### ISSUE TITLE
Kernel 4.12 restart during boot

### ISSUE THREAD

**Issue by emelcher** [maurossi/linux#9]
First I compiled with standard kernel using these commands:

`mkdir android-x86
cd android-x86
repo init -u http://scm.osdn.net/gitroot/android-x86/manifest -b marshmallow-x86
repo sync --no-tags --no-clone-bundle
export PATH=/usr/java/jdk1.7.0_80/bin:$PATH
. build/envsetup.sh
lunch android_x86_64-user
m -j6 iso_img`

Boot on my Positivo ZX3020 (CPU Z3735G) o.k., but no touch screen.
Linux (CentOS) with kernel 4.12 has touch screen working on this tablet.
I did  new compilation inserting the commands

`cd  kernel
git remote add maurossi https://github.com/maurossi/linux
git fetch maurossi kernel-4.12
git checkout FETCH_HEAD
cd ..`

after `repo sync`.

Booting in debug mode, the tablet restart after second exit.
Only a few lines appear and the screen becomes black immediately so I am unable to read anything.

Am I doing the compilation the right way?
How can I get detailed debugging log?

**Comment by emelcher** [comment]
The line feeds of the command sequence got lost, here they are again:

`mkdir android-x86

cd android-x86
export PATH=/usr/java/jdk1.7.0_80/bin:$PATH
repo init -u http://scm.osdn.net/gitroot/android-x86/manifest -b marshmallow-x86
repo sync --no-tags --no-clone-bundle
cd  kernel
git remote add maurossi https://github.com/maurossi/linux
git fetch maurossi kernel-4.12
git checkout FETCH_HEAD
cd ..
. build/envsetup.sh
lunch android_x86_64-user
m -j4 iso_img `

**Comment by maurossi** [comment]
Hi,
I'm having similar problem with kernel-4.13 and kernel-4.14rc(s)
with oreo-x86 (where in principle swiftshader should allow booting for any non drm HW accelerated like VESA boot option),
but during kernel release cycles I remember I could boot nougat with kernel-4.12 and kernel-4.13

I tried several times to submit dmesg commands without success, I need to try to use serial console with Null modem cable to see if I can get message output

I my case reboot happened with all GPUs and also in normal boot (not associated to DEBUG).
Mauro

**Comment by emelcher** [comment]
LineageOS compiled with kernel 4.15 resolves this issue.

`...`
`repo init -u git://git.osdn.net/gitroot/android-x86/manifest -b nougat-x86 -m cm.xml`
`...`
`git fetch maurossi kernel-4.15`
`...`

Touch screen is working now.
More details see http://lad.dsc.ufcg.edu.br/lad/pmwiki.php?n=Lad.Tablet
